"use client"

import { cn } from "@/lib/utils"

interface HeroBackgroundProps {
  children: React.ReactNode
  className?: string
}

/**
 * Decorative wrapper that adds a soft radial glow behind Hero + SocialProof.
 * Uses --gradient-color CSS variable (generated by generate-palette.py).
 *
 * Usage in page.tsx:
 *   <HeroBackground>
 *     <Hero />
 *     <SocialProof />
 *   </HeroBackground>
 */
export function HeroBackground({ children, className }: HeroBackgroundProps) {
  return (
    <div className={cn("relative w-full bg-background", className)}>
      {/* Soft radial glow — light mode: multiply blend, dark mode: screen blend */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 z-0 opacity-60 mix-blend-multiply dark:opacity-30 dark:mix-blend-screen"
        style={{
          backgroundImage:
            "radial-gradient(circle at center, hsl(var(--gradient-color)) 0%, transparent 70%)",
        }}
      />
      <div className="relative z-10">{children}</div>
    </div>
  )
}
